#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAProxy
echo '
frontend www-http
        bind *:80
        mode http
        default_backend www-backend
backend www-backend
        balance roundrobin
        server 223991-web-01 34.224.1.73 check
        server 223991-web-02 34.232.52.182 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
